# https://github.com/rust-lang/rust/blob/master/RELEASES.md
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2022-07-27"
components = ["cargo", "rustfmt", "clippy", "rust-src", "rust-std"]
