---
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: nix develop --command bash {0}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: build
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build package
        run: make build

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: fmt
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run formatters
        run: make fmt-ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: lint
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run linters
        run: make lint-ci

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: test
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run tests
        run: make test
